groups:
  - name: system_alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
          component: "{{ $labels.instance }}"
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
          dashboard_url: "https://grafana.justicebid.com/d/instance-health?var-instance={{ $labels.instance }}"
          runbook_url: "https://docs.justicebid.com/runbooks/instance-down"

      - alert: HighCPUUsage
        expr: avg by(instance) (rate(process_cpu_seconds_total[5m]) * 100) > 80
        for: 10m
        labels:
          severity: warning
          service: "{{ $labels.job }}"
          component: "system"
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has CPU usage above 80% for more than 10 minutes (current value: {{ $value }}%)."
          dashboard_url: "https://grafana.justicebid.com/d/system-resources?var-instance={{ $labels.instance }}"
          runbook_url: "https://docs.justicebid.com/runbooks/high-cpu-usage"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 10m
        labels:
          severity: warning
          service: "{{ $labels.job }}"
          component: "system"
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has memory usage above 85% for more than 10 minutes (current value: {{ $value }}%)."
          dashboard_url: "https://grafana.justicebid.com/d/system-resources?var-instance={{ $labels.instance }}"
          runbook_url: "https://docs.justicebid.com/runbooks/high-memory-usage"

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 85
        for: 10m
        labels:
          severity: warning
          service: "{{ $labels.job }}"
          component: "system"
        annotations:
          summary: "High disk usage on {{ $labels.instance }}:{{ $labels.mountpoint }}"
          description: "{{ $labels.instance }} has disk usage above 85% for more than 10 minutes (current value: {{ $value }}%)."
          dashboard_url: "https://grafana.justicebid.com/d/system-resources?var-instance={{ $labels.instance }}"
          runbook_url: "https://docs.justicebid.com/runbooks/high-disk-usage"

  - name: api_alerts
    rules:
      - alert: HighAPILatency
        expr: histogram_quantile(0.95, sum(rate(api_gateway_request_duration_seconds_bucket[5m])) by (le, service)) > 0.5
        for: 5m
        labels:
          severity: warning
          component: "api-gateway"
        annotations:
          summary: "High API latency for {{ $labels.service }}"
          description: "95th percentile of request duration for {{ $labels.service }} is above 500ms for more than 5 minutes (current value: {{ $value }}s)."
          dashboard_url: "https://grafana.justicebid.com/d/api-gateway-performance"
          runbook_url: "https://docs.justicebid.com/runbooks/high-api-latency"

      - alert: HighAPIErrorRate
        expr: sum(rate(api_gateway_http_requests_total{status=~"5.."}[5m])) by (service) / sum(rate(api_gateway_http_requests_total[5m])) by (service) > 0.01
        for: 5m
        labels:
          severity: warning
          component: "api-gateway"
        annotations:
          summary: "High API error rate for {{ $labels.service }}"
          description: "Error rate for {{ $labels.service }} is above 1% for more than 5 minutes (current value: {{ $value | humanizePercentage }})."
          dashboard_url: "https://grafana.justicebid.com/d/api-gateway-performance"
          runbook_url: "https://docs.justicebid.com/runbooks/high-api-error-rate"

      - alert: APIGatewaySLAViolation
        expr: histogram_quantile(0.95, sum(rate(api_gateway_request_duration_seconds_bucket[5m])) by (le)) > 0.5 and on() (day_of_week() >= 1 and day_of_week() <= 5 and hour() >= 8 and hour() < 18)
        for: 15m
        labels:
          severity: critical
          component: "api-gateway"
        annotations:
          summary: "API Gateway SLA violation"
          description: "API Gateway 95th percentile latency is above 500ms during business hours for more than 15 minutes (current value: {{ $value }}s). This violates the 99.95% availability SLA."
          dashboard_url: "https://grafana.justicebid.com/d/api-gateway-performance"
          runbook_url: "https://docs.justicebid.com/runbooks/api-sla-violation"

  - name: database_alerts
    rules:
      - alert: HighDatabaseLatency
        expr: histogram_quantile(0.95, sum(rate(database_query_duration_seconds_bucket[5m])) by (le, instance)) > 0.1
        for: 5m
        labels:
          severity: warning
          component: "database"
        annotations:
          summary: "High database query latency on {{ $labels.instance }}"
          description: "95th percentile of database query duration on {{ $labels.instance }} is above 100ms for more than 5 minutes (current value: {{ $value }}s)."
          dashboard_url: "https://grafana.justicebid.com/d/database-performance"
          runbook_url: "https://docs.justicebid.com/runbooks/high-database-latency"

      - alert: HighDatabaseConnections
        expr: sum(database_connections) by (instance) / sum(database_max_connections) by (instance) > 0.8
        for: 5m
        labels:
          severity: warning
          component: "database"
        annotations:
          summary: "High database connection usage on {{ $labels.instance }}"
          description: "Database connection pool usage on {{ $labels.instance }} is above 80% for more than 5 minutes (current value: {{ $value | humanizePercentage }})."
          dashboard_url: "https://grafana.justicebid.com/d/database-performance"
          runbook_url: "https://docs.justicebid.com/runbooks/high-database-connections"

      - alert: DatabaseSLAViolation
        expr: histogram_quantile(0.95, sum(rate(database_query_duration_seconds_bucket[5m])) by (le)) > 0.1 and on() (day_of_week() >= 1 and day_of_week() <= 5 and hour() >= 8 and hour() < 18)
        for: 15m
        labels:
          severity: critical
          component: "database"
        annotations:
          summary: "Database SLA violation"
          description: "Database 95th percentile query latency is above 100ms during business hours for more than 15 minutes (current value: {{ $value }}s). This violates the 99.99% availability SLA."
          dashboard_url: "https://grafana.justicebid.com/d/database-performance"
          runbook_url: "https://docs.justicebid.com/runbooks/database-sla-violation"

  - name: service_alerts
    rules:
      - alert: RateServiceHighErrorRate
        expr: sum(rate(http_requests_total{status=~"5..", service="rate-service"}[5m])) / sum(rate(http_requests_total{service="rate-service"}[5m])) > 0.01
        for: 5m
        labels:
          severity: warning
          service: "rate-service"
          component: "microservice"
        annotations:
          summary: "High error rate in Rate Service"
          description: "Rate Service error rate is above 1% for more than 5 minutes (current value: {{ $value | humanizePercentage }})."
          dashboard_url: "https://grafana.justicebid.com/d/services-performance?var-service=rate-service"
          runbook_url: "https://docs.justicebid.com/runbooks/rate-service-errors"

      - alert: NegotiationServiceHighErrorRate
        expr: sum(rate(http_requests_total{status=~"5..", service="negotiation-service"}[5m])) / sum(rate(http_requests_total{service="negotiation-service"}[5m])) > 0.01
        for: 5m
        labels:
          severity: warning
          service: "negotiation-service"
          component: "microservice"
        annotations:
          summary: "High error rate in Negotiation Service"
          description: "Negotiation Service error rate is above 1% for more than 5 minutes (current value: {{ $value | humanizePercentage }})."
          dashboard_url: "https://grafana.justicebid.com/d/services-performance?var-service=negotiation-service"
          runbook_url: "https://docs.justicebid.com/runbooks/negotiation-service-errors"

      - alert: AnalyticsServiceHighErrorRate
        expr: sum(rate(http_requests_total{status=~"5..", service="analytics-service"}[5m])) / sum(rate(http_requests_total{service="analytics-service"}[5m])) > 0.01
        for: 5m
        labels:
          severity: warning
          service: "analytics-service"
          component: "microservice"
        annotations:
          summary: "High error rate in Analytics Service"
          description: "Analytics Service error rate is above 1% for more than 5 minutes (current value: {{ $value | humanizePercentage }})."
          dashboard_url: "https://grafana.justicebid.com/d/services-performance?var-service=analytics-service"
          runbook_url: "https://docs.justicebid.com/runbooks/analytics-service-errors"

      - alert: IntegrationServiceHighErrorRate
        expr: sum(rate(http_requests_total{status=~"5..", service="integration-service"}[5m])) / sum(rate(http_requests_total{service="integration-service"}[5m])) > 0.01
        for: 5m
        labels:
          severity: warning
          service: "integration-service"
          component: "microservice"
        annotations:
          summary: "High error rate in Integration Service"
          description: "Integration Service error rate is above 1% for more than 5 minutes (current value: {{ $value | humanizePercentage }})."
          dashboard_url: "https://grafana.justicebid.com/d/services-performance?var-service=integration-service"
          runbook_url: "https://docs.justicebid.com/runbooks/integration-service-errors"

  - name: service_sla_alerts
    rules:
      - alert: RateServiceSLAViolation
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service="rate-service"}[5m])) by (le)) > 1 and on() (day_of_week() >= 1 and day_of_week() <= 5 and hour() >= 8 and hour() < 18)
        for: 15m
        labels:
          severity: critical
          service: "rate-service"
          component: "microservice"
        annotations:
          summary: "Rate Service SLA violation"
          description: "Rate Service 95th percentile latency is above 1s during business hours for more than 15 minutes (current value: {{ $value }}s). This violates the 99.9% availability SLA."
          dashboard_url: "https://grafana.justicebid.com/d/services-performance?var-service=rate-service"
          runbook_url: "https://docs.justicebid.com/runbooks/rate-service-sla-violation"

      - alert: NegotiationServiceSLAViolation
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service="negotiation-service"}[5m])) by (le)) > 1 and on() (day_of_week() >= 1 and day_of_week() <= 5 and hour() >= 8 and hour() < 18)
        for: 15m
        labels:
          severity: critical
          service: "negotiation-service"
          component: "microservice"
        annotations:
          summary: "Negotiation Service SLA violation"
          description: "Negotiation Service 95th percentile latency is above 1s during business hours for more than 15 minutes (current value: {{ $value }}s). This violates the 99.9% availability SLA."
          dashboard_url: "https://grafana.justicebid.com/d/services-performance?var-service=negotiation-service"
          runbook_url: "https://docs.justicebid.com/runbooks/negotiation-service-sla-violation"

      - alert: AnalyticsServiceSLAViolation
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service="analytics-service"}[5m])) by (le)) > 3 and on() (day_of_week() >= 1 and day_of_week() <= 5 and hour() >= 8 and hour() < 18)
        for: 15m
        labels:
          severity: critical
          service: "analytics-service"
          component: "microservice"
        annotations:
          summary: "Analytics Service SLA violation"
          description: "Analytics Service 95th percentile latency is above 3s during business hours for more than 15 minutes (current value: {{ $value }}s). This violates the 99.5% availability SLA."
          dashboard_url: "https://grafana.justicebid.com/d/services-performance?var-service=analytics-service"
          runbook_url: "https://docs.justicebid.com/runbooks/analytics-service-sla-violation"

      - alert: IntegrationServiceSLAViolation
        expr: sum(rate(integration_jobs_total{status="success"}[1h])) by (job_type) / sum(rate(integration_jobs_total[1h])) by (job_type) < 0.99 and on() (day_of_week() >= 1 and day_of_week() <= 5 and hour() >= 8 and hour() < 18)
        for: 15m
        labels:
          severity: critical
          service: "integration-service"
          component: "microservice"
        annotations:
          summary: "Integration Service SLA violation for {{ $labels.job_type }}"
          description: "Integration Service success rate for {{ $labels.job_type }} is below 99% during business hours for more than 15 minutes (current value: {{ $value | humanizePercentage }}). This violates the 99.5% availability SLA."
          dashboard_url: "https://grafana.justicebid.com/d/services-performance?var-service=integration-service"
          runbook_url: "https://docs.justicebid.com/runbooks/integration-service-sla-violation"