# Development environment configuration for Justice Bid Rate Negotiation System
# This file defines development-specific settings for Kubernetes deployment

# Environment Settings
ENVIRONMENT: development
LOG_LEVEL: DEBUG
FLASK_ENV: development
DEBUG: "true"

# API Configuration
VITE_API_URL: http://localhost:8080/api
CORS_ORIGINS: http://localhost:3000,http://justicebid.local
API_RATE_LIMIT: "100"
SESSION_TIMEOUT: "7200"

# Service Hostnames
DATABASE_HOST: postgres-service
MONGODB_HOST: mongodb-service
REDIS_HOST: redis-service
RABBITMQ_HOST: rabbitmq-service
AI_SERVICE_HOST: ai-service
ANALYTICS_SERVICE_HOST: analytics-service
INTEGRATION_SERVICE_HOST: integration-service

# Message Queue Configuration
CELERY_BROKER_URL: amqp://rabbitmq-service:5672
CELERY_RESULT_BACKEND: redis://redis-service:6379/0

# Resource Limits - Development environment (Small: 8 vCPUs, 32 GB RAM)
RESOURCE_LIMITS:
  BACKEND_CPU: 500m
  BACKEND_MEMORY: 1Gi
  FRONTEND_CPU: 200m
  FRONTEND_MEMORY: 512Mi
  ANALYTICS_CPU: 1000m
  ANALYTICS_MEMORY: 2Gi
  AI_CPU: 1000m
  AI_MEMORY: 2Gi
  CELERY_CPU: 500m
  CELERY_MEMORY: 1Gi
  INTEGRATION_CPU: 500m
  INTEGRATION_MEMORY: 1Gi

# Replica Configuration for Development
REPLICAS:
  BACKEND: "1"
  FRONTEND: "1"
  ANALYTICS: "1"
  AI: "1"
  CELERY: "1"
  INTEGRATION: "1"