apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: justice-bid-production
namePrefix: prod-

commonLabels:
  environment: production
  tier: production

configMapGenerator:
  - name: justice-bid-config
    files:
      - config.yaml

secretGenerator:
  - name: justice-bid-secrets
    envs:
      - .env.production

images:
  - name: justicebid/frontend
    newName: justicebid/frontend
    newTag: v1.0.0
  - name: justicebid/api-gateway
    newName: justicebid/api-gateway
    newTag: v1.0.0
  - name: justicebid/rate-service
    newName: justicebid/rate-service
    newTag: v1.0.0
  - name: justicebid/negotiation-service
    newName: justicebid/negotiation-service
    newTag: v1.0.0
  - name: justicebid/analytics-service
    newName: justicebid/analytics-service
    newTag: v1.0.0
  - name: justicebid/integration-service
    newName: justicebid/integration-service
    newTag: v1.0.0
  - name: justicebid/ai-service
    newName: justicebid/ai-service
    newTag: v1.0.0
  - name: justicebid/document-service
    newName: justicebid/document-service
    newTag: v1.0.0
  - name: justicebid/messaging-service
    newName: justicebid/messaging-service
    newTag: v1.0.0

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: frontend
    patch:
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: '2'
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: '4Gi'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: '1'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: '2Gi'
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: api-gateway
    patch:
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: '4'
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: '8Gi'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: '2'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: '4Gi'
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: rate-service
    patch:
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: '4'
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: '8Gi'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: '2'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: '4Gi'
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: negotiation-service
    patch:
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: '4'
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: '8Gi'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: '2'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: '4Gi'
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: analytics-service
    patch:
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: '8'
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: '16Gi'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: '4'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: '8Gi'
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ai-service
    patch:
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: '8'
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: '16Gi'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: '4'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: '8Gi'

replicas:
  - name: frontend
    count: 6
  - name: api-gateway
    count: 8
  - name: rate-service
    count: 8
  - name: negotiation-service
    count: 8
  - name: analytics-service
    count: 6
  - name: integration-service
    count: 6
  - name: ai-service
    count: 4
  - name: document-service
    count: 4
  - name: messaging-service
    count: 6